services:
  github-fork-syncer:
    build:
      context: https://github.com/dynacylabs/github_fork_syncer.git
      dockerfile: Dockerfile
    container_name: github-fork-syncer
    env_file:
      - example.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
