services:
  github-fork-syncer:
    build:
      context: https://github.com/dynacylabs/github_fork_syncer.git
      dockerfile: Dockerfile
    container_name: github-fork-syncer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "-v", "grep", "|", "grep", "crond"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
